{"name": "testclass_002", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 100", "trace": "self = <test_demo02.TestClass object at 0x000001ECD34E02B0>\n\n    def testclass_002(self):\n        print(\"-----------testclass_002--------------\")\n>       assert 1 == 100\nE       assert 1 == 100\n\ntestcase\\test_demo02.py:15: AssertionError"}, "attachments": [{"name": "stdout", "source": "c81f82b6-b65f-4ddc-9950-bfb3be958519-attachment.txt", "type": "text/plain"}], "start": 1690421609624, "stop": 1690421609625, "uuid": "d1e6f821-c075-47ee-8156-dce5a743db22", "historyId": "b7b25fd3b009a1919de005c2caa6d650", "testCaseId": "869435395fa9305b59cf5fc121c072c8", "fullName": "testcase.test_demo02.TestClass#testclass_002", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo02"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "zhanghao"}, {"name": "thread", "value": "12196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo02"}]}